# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='postal_code',
            field=models.CharField(default='111111', max_length=6),
        ),
    ]
