# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_userprofileinfo_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('80', '80% New'), ('Obsolete', 'Obsolete')], default='Used', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
