# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20171015_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='condition',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
